// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

def repoName =  'origin'

node {
    stage 'Checkout'
    checkout(
        changelog: true,
        poll: true,
        scm: [
            $class: 'GitSCM',
            branches: [[name: "${repoName}/${SOURCE_BRANCH}"]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [
                [$class: 'WipeWorkspace'],
                [$class: 'PruneStaleBranch'],
                [$class: 'SubmoduleOption', disableSubmodules: false, recursiveSubmodules: true, reference: '', trackingSubmodules: false],
                [$class: 'PreBuildMerge', options: [
                    fastForwardMode: 'FF',
                    mergeRemote: 'origin',
                    mergeStrategy: 'default',
                    mergeTarget: DESTINATION_BRANCH
                ]], 
                [$class: 'AuthorInChangelog']
            ],
            submoduleCfg: [],
            userRemoteConfigs: [[name: repoName, url: REPO_URI]]
        ]
    )

    stage 'Build Java'
    withCredentials([
        [$class: 'StringBinding', credentialsId: '05294bb0-93c3-4f01-a258-666586a3917c', variable: 'IOTHUB_CONNECTION_STRING'],
        [$class: 'StringBinding', credentialsId: '4a97c867-c403-4c77-839b-5eabf39feafe', variable: 'STORAGE_ACCOUNT_CONNECTION_STRING']])
    {
        sh 'jenkins/linux_java.sh'
    }

    stage 'Publish to repository'
    // This is currently the best way to push a tag (or a branch, etc) from a
    // Pipeline job. It's not ideal - https://issues.jenkins-ci.org/browse/JENKINS-28335
    // is an open JIRA for getting the GitPublisher Jenkins functionality working
    // with Pipeline.
    // see https://github.com/jenkinsci/pipeline-examples/blob/master/pipeline-examples/push-git-repo/pushGitRepo.Groovy
    withCredentials([[
        $class: 'UsernamePasswordMultiBinding',
        credentialsId: 'cf1ac13d-fc43-450b-9d4d-8352086aa522',
        usernameVariable: 'GITUSR',
        passwordVariable: 'GITPASSWD']])
    {
        sh 'jenkins/jenkins_push.sh'
    }
}
