// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

def repoUrl = 'https://github.com/damonbarry/azure-iot-sdks.git'
def repoName =  'origin'
def branchName = 'develop'

node {
    stage 'Checkout'
    checkout([
        $class: 'GitSCM',
        branches: [[name: "${repoName}/${branchName}"]],
        doGenerateSubmoduleConfigurations: false,
        extensions: [
            [$class: 'WipeWorkspace'],
            [$class: 'PruneStaleBranch'],
            [$class: 'SubmoduleOption', disableSubmodules: false, recursiveSubmodules: true, reference: '', trackingSubmodules: false]
        ],
        submoduleCfg: [],
        userRemoteConfigs: [[name: repoName, url: repoUrl]]
    ])

    stage 'Build Java'
    sh 'jenkins/linux_java.sh'
}
